timeout = 30
cursorclass="pymysql.cursors.DictCursor"
db="defaultdb"
host="mysql-a54ef6c-toureadama-2bc0.c.aivencloud.com"
password="AVNS_O9FSI98GLiPqRHk5e0H"
read_timeout = 30
port=15107
user="avnadmin"